config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'pages#top'
  devise_for :users
  post '/pages/guest_sign_in', to: 'pages#guest_sign_in'
  post '/pages/admin_guest_sign_in', to: 'pages#admin_guest_sign_in'
  get 'top', to: 'pages#top', as: :top 
  get 'user/:id/my_page', to: 'pages#my_page', as: :my_page 
  resources :projects, shallow: true do
    resources :themes, except: :show
    collection do
      get 'search'
    end
    member do
      get 'public_on', to: 'projects#public_on', as: :public_on 
      get 'public_off', to: 'projects#public_off', as: :public_off 
    end
  end
  get 'user/:user_id/theme/:id', to: 'themes#show', as: :three 
  get 'threee/slide', to: 'pages#slide', as: :slide 
  resources :favorites, only: %i[index create destroy]
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
end

app/models/theme.rb
class Theme < ApplicationRecord
  validates :first_theme, presence: true, length: { in: 1..255 }
  validates :second_theme, presence: true, length: { in: 1..255 }
  validates :third_theme, presence: true, length: { in: 1..255 }
  belongs_to :project
  has_one :user, through: :project
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, presence: true, length: { in: 1..255 }
  validates :email, presence: true, length: { in: 1..255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects, dependent: :destroy
  has_many :themes, through: :projects
  has_many :favorites, dependent: :destroy
  has_many :favorite_projects, through: :favorites, source: :project
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :set_theme, only: %i[ show edit update ]
  before_action :check_user, only: %i[edit update destory]
  skip_before_action :authenticate_user!, only: :show

  def index
    @project = Project.find(params[:project_id])
    @user = @project.user
    @themes = @project.themes.order(created_at: :desc)
  end

  def new
    @project = Project.find(params[:project_id])
    @user = @project.user
    @now_theme = @project.themes.order(created_at: :desc).first
    @theme = Project.find(params[:project_id]).themes.order(created_at: :desc).first.dup
  end

  def show
    @user = @theme.project.user
    @themes = @theme.project.themes.order(created_at: :desc)
    @now_theme = @themes.first
    @theme_ids = @themes.map{|t| t.id }
    @theme_ids_num = @theme_ids.index(@theme.id)
    @back_id = @theme_ids[@theme_ids.index(@theme.id)+1]
    @next_id = @theme_ids[@theme_ids.index(@theme.id)-1]
    @back_id ||= @theme_ids[@theme_ids.index(@theme.id)]
    @next_id ||= @theme_ids[@theme_ids.index(@theme.id)]
  end

  def edit
    @project = @theme.project
    @user = @project.user
    @now_theme = @project.themes.order(created_at: :desc).first
  end

  def create
    @project = Project.find(params[:project_id])
    @user = @project.user
    @theme = @project.themes.new(theme_params)
    

    respond_to do |format|
      if equal_now(@theme, @project.themes.order(created_at: :desc).first)
        format.html { redirect_to new_project_theme_path, notice: "現在のテーマと同じです"}
      elsif @theme.save
        format.html { redirect_to three_path(@user, @theme), notice: "テーマが変更されました" }
        format.json { render :show, status: :created, location: @theme }
      else
        format.html {redirect_to new_project_theme_path, notice: "テーマの変更に失敗しました" }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @user = @theme.user
    respond_to do |format|
      if @theme.update(theme_params)
        format.html { redirect_to three_path(@user, @theme), notice: "テーマが修正されました" }
        format.json { render :show, status: :ok, location: @theme }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def check_user
    unless @theme.project.user_id == current_user.id
      redirect_to my_page_path(@theme.project.user_id), notice: '他のユーザーではできない処理です'
    end
  end

  def set_theme
    @theme = Theme.find(params[:id])
  end

  def theme_params
    params.require(:theme).permit(:first_theme, :second_theme, :third_theme)
  end

  def equal_now(new, now)
    new.first_theme == now.first_theme && new.second_theme == now.second_theme && new.third_theme == now.third_theme
  end

end

app/helpers/themes_helper.rb
module ThemesHelper
  def form_url
    if action_name == "new"
      project_themes_path
    elsif action_name == "edit"
      theme_path
    end
  end
end

app/views/themes/_form.html.erb
<%= form_with(model: theme, url: form_url) do |form| %>
  <% if theme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(theme.errors.count, "error") %> prohibited this theme from being saved:</h2>
      <ul>
        <% theme.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions field">
    __
  </div>
  
  <div class="actions field">
    <%= form.submit %>
  </div>

  <div>
    <ul>
      <li>
        <h3>
          <div class="field">
            <%= form.text_field :first_theme ,class: "theme_field"%>
          </div>
        </h3>
      </li>
      <li>
        <h3>
          <div class="field">
            <%= form.text_field :second_theme ,class: "theme_field"%>
          </div>
        </h3>
      </li>
      <li>
        <h3>
          <div class="field">
            <%= form.text_field :third_theme  ,class: "theme_field"%>
          </div>
        </h3>
      </li>
    </ul>
  </div>
<% end %>

app/views/themes/edit.html.erb
<div class="field center">
  <h1 style="opacity: 0.4;">👤</h1>
  <%= link_to '現在のテーマ', three_path(@user, @theme) %>
</div>
<div class="field center">
  <h2><%= @theme.project.title %></h2>
</div>

<p>
  <div class="field center">
    <%= @theme.created_at.in_time_zone('Tokyo').strftime("%Y年%m月%d日 %H:%M:%S") %>
  </div>
</p>
<div class="field cenetr">
  |
</div>



<%= render 'form', {theme: @theme, project: @theme.project} %>

app/views/themes/index.html.erb
<div class="field">
  <h1>履歴</h1>
  <table class="field">
    <thead>
      <tr>
        <th>テーマ　①</th>
        <th>テーマ　②</th>
        <th>テーマ　③</th>
        <th></th>
      </tr>
    </thead>
  
    <tbody>
      <% @themes.each do |theme| %>
        <tr>
          <td><%= theme.first_theme %></td>
          <td><%= theme.second_theme %></td>
          <td><%= theme.third_theme %></td>
          <td><%= theme.created_at.in_time_zone('Tokyo').strftime("%Y年%m月%d日 %H:%M:%S") %></td>
          <td><%= link_to '詳細', three_path(@user, theme) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <br>
  
  <%= link_to 'New Theme', new_project_theme_path(@project) %>
</div>

app/views/themes/new.html.erb
<div class="field center">
  <h1>👤</h1>
  <%= link_to '現在のテーマ', three_path(@user, @now_theme) %>
</div>

<div class="field center">
  <h2><%= @project.title %></h2>
</div>

<p>
  <div class="field center">
    <%= @now_theme.created_at.in_time_zone('Tokyo').strftime("%Y年%m月%d日 %H:%M:%S") %>
  </div>
</p>

<div class="field cenetr">
  |
</div>

<%= render 'form', {theme: @theme, project: @project} %>

app/views/themes/show.html.erb
<div class="field center">
  <% if current_user == nil %>
  <% elsif @user != current_user %>
    <% if Favorite.exists?(user_id: current_user, project_id: @theme.project.id) %>
      <%= render 'projects/non_favorite', {project: @theme.project} %>
    <% else %>
      <%= render 'projects/favorite', {project: @theme.project} %>
    <% end %>
  <% elsif @now_theme.id == @theme.id %>
    <h1>👤</h1>
    <%= link_to '現在のテーマを変更する', new_project_theme_path(@theme.project) %>
  <% else %>
    <h1 style="opacity: 0.4;">👤</h1>
    <%= link_to '過去のテーマを修正する', edit_theme_path(@theme) %>
  <% end %>
</div>

<div class="field center">
  <h2><%= @theme.project.title %></h2>
</div>

<p>
  <div class="field center">
    <%= @theme.created_at.in_time_zone('Tokyo').strftime("%Y年%m月%d日 %H:%M:%S") %>
  </div>
</p>

<div class="field cenetr">
  <% if @theme_ids_num != @theme_ids.length-1 %>
    <%= link_to '前へ', three_path(@user, @back_id) %>
  <% end %>
  |
  <% if @theme_ids_num != 0 %>
    <%= link_to '次へ', three_path(@user, @next_id) %>
  <% end %>
</div>
<p>
  <div class="field center">
    <%= @theme_ids_num + 1 %> / <%= @theme_ids.length%>
    <% if @theme_ids_num == 0 %>
      (現在)
    <% else %>
      (過去)
    <% end %>
  </div>
</p>

<ul>
  <li>
    <h3>
      <div class="field center">
        <%= @theme.first_theme %>
      </div>
    </h3>
  </li>
  
  <li>
    <h3>
      <div class="field center">
        <%= @theme.second_theme %>
      </div>
    </h3>
  </li>
  
  <li>
    <h3>
      <div class="field cenetr">
        <%= @theme.third_theme %>
      </div>
    </h3>
  </li>
  
</ul>

<div class="field cenetr">
  <%= link_to 'プロジェクトリストに戻る',  projects_path %>
</div>

<div class="field cenetr">
  <% unless current_user == nil %>    
  <%= link_to '履歴', project_themes_path(@theme.project) %>
  <% end %>
</div>