config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'pages#top'
  devise_for :users
  post '/pages/guest_sign_in', to: 'pages#guest_sign_in'
  post '/pages/admin_guest_sign_in', to: 'pages#admin_guest_sign_in'
  get 'top', to: 'pages#top', as: :top 
  get 'user/:id/my_page', to: 'pages#my_page', as: :my_page 
  resources :projects, shallow: true do
    resources :themes, except: :show
    collection do
      get 'search'
    end
    member do
      get 'public_on', to: 'projects#public_on', as: :public_on 
      get 'public_off', to: 'projects#public_off', as: :public_off 
    end
  end
  get 'user/:user_id/theme/:id', to: 'themes#show', as: :three 
  get 'threee/slide', to: 'pages#slide', as: :slide 
  resources :favorites, only: %i[index create destroy]
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
end

app/views/pages/my_page.html.erb
<div class="field">
  <h1><%= @user.name %>さんのマイページ</h1>
  
  <h3><%= link_to 'お気に入りのプロジェクト', favorites_path %></h3>
  <table class="field table-fixed">
    <thead>
      <tr>
        <th>公開</th>
        <th class="col-8">タイトル</th>
        <th class="col-1"></th>
        <th></th>
        <th></th>
        <th>変更回数</th>
        <th>作成日時</th>
      </tr>
    </thead>
  
    <tbody>
      <% @projects.each do |project| %>
        <tr>
          <td>
            <% if project.public %>
              <%= render 'projects/public', {project: project} %>
            <% else %>
              <%= render 'projects/private', {project: project} %>
            <% end %>
          </td>
          <td>
            <h3>
              <% if project.themes.count==0 %>
                <%= link_to project.title, new_project_path %>
              <% else %>
                <%= link_to project.title, three_path(@user.id, project.themes.order(created_at: :desc).first.id) %>
              <% end %>
            </h3>
          </td>
          <td>
            <p><%= link_to '名前を編集する', edit_project_path(project) %></p>
          </td>
          <td>
            <p><%= link_to '削除する', project, method: :delete, data: { confirm: '本当に削除しますか？' } %></p>
          </td>
          <td><%= link_to '履歴', project_themes_path(project) %></td>
          <td><%= project.themes.length %></td>
          <td><%= project.created_at.in_time_zone('Tokyo').strftime("%Y年%m月%d日 %H:%M:%S") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <br>
  
  
  <%= link_to '新規作成', new_project_path %>
  
</div>

app/views/pages/slide.html.erb
  <p>
    <button id="enterFullscreen">フルスクリーンで見る</button>
  </p>
<div id="content">
  <!-- 001
  <p>
    <button id="exitFullscreen" >フルスクリーンを解除</button>
  </p>
  -->
  <div class="slider">
    <div class="slides">
      <div class="slide-contents grd"  tabindex="0">
        <br>
        <h1 class="title-8">Threee</h1>
        <br>
        <p class="title-3">7月期生：大塚昂士</p>
      </div>
      <div class="slide-contents grd"  tabindex="0">
      <p class="title-5 grd">目次</p>
        <ul>
        <li class="title-3 margin-10">アプリケーションの使い方</li>
        <li class="title-3">アプリケーション開発のきっかけ</li>
        <li class="title-3">その他（こだわりポイント、使用した技術など）</li>
        </ul>
      </div>
      <div class="slide-contents grd"  tabindex="0">
        <p class="title-5">アプリケーションの使い方</p>
      </div>
      <div class="slide-contents"  tabindex="0">
        <p class="title-5">アプリケーションの使い方</p>
        <ol>
        <li class="title-3 margin-10">三つのテーマを上げる</li>
        <li class="title-3">三つのテーマをもとに取り組む</li>
        <li class="title-3">ふとした時に三つのテーマを振り返る</li>
        </ol>
      </div>
      <div class="slide-contents"  tabindex="0">
      <p class="title-5">アプリケーションの使い方</p>
        <ol>
        <li class="title-3 margin-10">三つのテーマを上げる</li>
        <li class="title-3  gray-b">三つのテーマをもとに取り組む</li>
        <li class="title-3 gray-b">ふとした時に三つのテーマを振り返る</li>
        </ol>
      </div>
      <div class="slide-contents"  tabindex="0">
        <p class="title-5">プログラミングの学習</p>
        <p class="title-3 margin-10 gray-b">テーマ①</p>
        <p class="title-3 gray-b">テーマ②</p>
        <p class="title-3 gray-b">テーマ③</p>
      
      </div>
      <div class="slide-contents"  tabindex="0">
        <p class="title-5">プログラミングの学習</p>
        <p class="title-3 margin-10 bluegray">時間をはかる</p>
        <p class="title-3 gray-b">テーマ②</p>
        <p class="title-3 gray-b">テーマ③</p>
      </div>

      <div class="slide-contents"  tabindex="0">
        <p class="title-5">プログラミングの学習</p>
        <p class="title-3 margin-10 gray-b">時間をはかる</p>
        <p class="title-3 bluegray">姿勢に気をつける</p>
        <p class="title-3 gray-b">テーマ③</p>
      </div>
      <div class="slide-contents"  tabindex="0">
        <p class="title-5">プログラミングの学習</p>
        <p class="title-3 margin-10 gray-b">時間をはかる</p>
        <p class="title-3 gray-b">姿勢に気を付ける</p>
        <p class="title-3 bluegray">定期的に水を飲む</p>
      </div>
      <div class="slide-contents"  tabindex="0">
        <p class="title-5">プログラミングの学習</p>
        <p class="title-3 margin-10">時間をはかる</p>
        <p class="title-3">姿勢に気を付ける</p>
        <p class="title-3">定期的に水を飲む</p>
      </div>
      <div class="slide-contents"  tabindex="0">
        <p class="title-5">プログラミングの学習</p>
        <p class="title-3 margin-10">時間をはかる</p>
        <p class="title-3">姿勢に気を付ける</p>
        <p class="title-3">定期的に水を飲む</p>
        <p class="">↑</p>
        <p class="title-3 blue">閲覧できるヨ！！</p>
      </div>
      <div class="slide-contents"  tabindex="0">
      <p class="title-5">アプリケーションの使い方</p>
        <ol>
        <li class="title-3 margin-10 gray-b">三つのテーマを上げる</li>
        <li class="title-3">三つのテーマをもとに取り組む</li>
        <li class="title-3 gray-b">ふとした時に三つのテーマを振り返る</li>
        </ol>
      </div>
      <div class="slide-contents"  tabindex="0">
        <p class="title-5">プログラミングの学習</p>
        <p class="title-3 margin-10">時間をはかる</p>
        <p class="title-3">姿勢に気を付ける</p>
        <p class="title-3">定期的に水を飲む</p>
      </div>
      <div class="slide-contents"  tabindex="0">
        <p class="title-5">💻プログラミングの学習</p>
        <p class="title-3 margin-10">🕛時間をはかる</p>
        <p class="title-3">🪑姿勢に気を付ける</p>
        <p class="title-3">🚰定期的に水を飲む</p>
      </div>
      <div class="slide-contents"  tabindex="0">
        <p class="title-5 pos0 center-0">💻</p>
      </div>
      <div class="slide-contents"  tabindex="0">
        <p class="title-5 pos0 center-0">💻</p>
        <p class="title-3 pos0 tri-1">🕛</p>
        <p class="title-3 pos0 tri-2">🪑</p>
        <p class="title-3 pos0 tri-3">🚰</p>
        <p class="circle-notice"></p>

      </div>
      <div class="slide-contents"  tabindex="0">
      <p class="title-5">アプリケーションの使い方</p>
        <ol>
        <li class="title-3 margin-10 gray-b">三つのテーマを上げる</li>
        <li class="title-3 gray-b">三つのテーマをもとに取り組む</li>
        <li class="title-3">ふとした時に三つのテーマを振り返る</li>
        </ol>
      </div>
      <div class="slide-contents"  tabindex="0">
        <p class="title-5">プログラミングの学習</p>
        <p class="title-3 margin-10">時間をはかる</p>
        <p class="title-3">姿勢に気を付ける</p>
        <p class="title-3">定期的に水を飲む</p>
      </div>
      <div class="slide-contents"  tabindex="0">
        <p class="title-5">プログラミングの学習</p>
        <p class="title-3 margin-10 bluegray">時間をはかる</p>
        <p class="title-3 gray-b">姿勢に気を付ける</p>
        <p class="title-3 gray-b">定期的に水を飲む</p>
      </div>
      <div class="slide-contents"  tabindex="0">
        <p class="title-5">プログラミングの学習</p>
        <p class="title-3 margin-10 bluegray">|</p>
        <p class="title-3 gray-b">姿勢に気を付ける</p>
        <p class="title-3 gray-b">定期的に水を飲む</p>
      </div>
      <div class="slide-contents"  tabindex="0">
        <p class="title-5">プログラミングの学習</p>
        <p class="title-3 margin-10 green">集中力を高める</p>
        <p class="title-3 gray-b">姿勢に気を付ける</p>
        <p class="title-3 gray-b">定期的に水を飲む</p>
      </div>
      <div class="slide-contents title-2"  tabindex="0">
        <h1>履歴</h1>
        <table class="field">
          <thead>
            <tr>
              <th>テーマ　①</th>
              <th>テーマ　②</th>
              <th>テーマ　③</th>
              <th></th>
            </tr>
          </thead>
        
          <tbody>
              <tr>
                <td>集中力を高める</td>
                <td>姿勢に気を付ける</td>
                <td>定期的に水を飲む</td>
                <td>変更後</td>
              </tr>
              <tr>
                <td>時間をはかる</td>
                <td>姿勢に気を付ける</td>
                <td>定期的に水を飲む</td>
                <td>変更前</td>
              </tr>
          </tbody>
        </table>
      </div>
      <div class="slide-contents title-2"  tabindex="0">
        <h1>履歴</h1>
        <table class="field">
          <thead>
            <tr>
              <th>テーマ　①</th>
              <th>テーマ　②</th>
              <th>テーマ　③</th>
              <th></th>
            </tr>
          </thead>
        
          <tbody>
              <tr>
                <td class="green">集中力を高める</td>
                <td class="gray-b">姿勢に気を付ける</td>
                <td class="gray-b">定期的に水を飲む</td>
                <td class="green">変更後</td>
              </tr>
              <tr>
                <td class="bluegray">時間をはかる</td>
                <td class="gray-b">姿勢に気を付ける</td>
                <td class="gray-b">定期的に水を飲む</td>
                <td class="bluegray">変更前</td>
              </tr>
          </tbody>
        </table>
      </div>
      <div class="slide-contents"  tabindex="0">
      <p class="title-5">アプリケーションの使い方</p>
        <ol>
        <li class="title-3 margin-10">三つのテーマを上げる</li>
        <li class="title-3">三つのテーマをもとに取り組む</li>
        <li class="title-3">ふとした時に三つのテーマを振り返る</li>
        </ol>
      </div>
      <div class="slide-contents grd"  tabindex="0">
        <p class="title-5">アプリケーションについて</p>
      </div>
      <div class="slide-contents"  tabindex="0">
      <p class="title-5">制作期間：約3週間</p>
        <ul>
        <li class="title-3 margin-10">要件定義合格：約2週間</li>
        <li class="title-3">卒業課題合格：約1週間</li>
        <li class="title-3">卒業発表準備：約1/2週間</li>
        </ul>
      </div>
      <div class="slide-contents"  tabindex="0">
      <p class="title-5">こだわりポイント</p>
        <ul>
        <li class="title-3 margin-10">履歴機能</li>
        <li class="title-3">お気に入り機能</li>
        <li class="title-3">公開機能</li>
        </ul>
      </div>
      <div class="slide-contents"  tabindex="0">
      <p class="title-5">苦労した点</p>
        <ul>
        <li class="title-3 margin-10">テーブル設計（履歴機能）</li>
        <li class="title-3">履歴機能を実装する際にページを把握するのに時間がかかった</li>
        </ul>
      </div>
      <div class="slide-contents"  tabindex="0">
      <p class="title-5">使用した技術</p>
        <ul>
        <li class="title-3 margin-10">AWS EC2（デプロイ）</li>
        <li class="title-3">Ajax, JQuery（お気に入り機能、公開機能）</li>
        <li class="title-3">Bootstrap（デザイン）</li>
        <li class="title-3">gem ‘devise’（ログイン機能）</li>
        <li class="title-3">gem ‘ransack’（タイトル検索機能）</li>
        </ul>
      </div>
      <div class="slide-contents"  tabindex="0">
      <p class="title-5">今後の展望</p>
        <ul>
        <li class="title-3 margin-10">メモ機能（自分のプロジェクトに対しての）</li>
        <li class="title-3">時間表示機能</li>
        <li class="title-3">試行回数表示機能</li>
        </ul>
      </div>
      <div class="slide-contents"  tabindex="0">
      <p class="title-5">クロージングへ</p>
      </div>
      <div class="slide-contents"  tabindex="0">
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(function(){
    $("#enterFullscreen").on("click", function() {
      var x = document.getElementById("content");
      if (x.webkitRequestFullScreen) {
        x.webkitRequestFullScreen();
      } else if (x.mozRequestFullScreen) {
        x.mozRequestFullScreen();
      } else {
        x.requestFullScreen();
      }
    })
  // //001
  //   $("#exitFullscreen").on("click", function() {
  //     if (document.webkitCancelFullScreen) {
  //       document.webkitCancelFullScreen();
  //     } else if (document.mozCancelFullScreen) {
  //       document.mozCancelFullScreen();
  //     } else {
  //       document.exitFullscreen();
  //     }
  //   })
  })
  
</script>

app/views/pages/time.html.erb
<h1 id="time"></h1>
<p>
</p>
<select name="num">
<option value="">-</option>
<option value="0">0</option>
<option value="1">1</option>
<option value="2">2</option>
<option value="3">3</option>
<option value="4">4</option>
<option value="5">5</option>
<option value="6">6</option>
<option value="7">7</option>
<option value="8">8</option>
<option value="9">9</option>
<option value="10">10</option>
<option value="11">11</option>
<option value="12">12</option>
<option value="13">13</option>
<option value="14">14</option>
<option value="15">15</option>
<option value="16">16</option>
<option value="17">17</option>
<option value="18">18</option>
<option value="19">19</option>
<option value="20">20</option>
<option value="21">21</option>
<option value="22">22</option>
<option value="23">23</option>
<option value="24">24</option>
<option value="25">25</option>
<option value="26">26</option>
<option value="27">27</option>
<option value="28">28</option>
<option value="29">29</option>
<option value="30">30</option>
<option value="31">31</option>
<option value="32">32</option>
<option value="33">33</option>
<option value="34">34</option>
<option value="35">35</option>
<option value="36">36</option>
<option value="37">37</option>
<option value="38">38</option>
<option value="39">39</option>
<option value="40">40</option>
<option value="41">41</option>
<option value="42">42</option>
<option value="43">43</option>
<option value="44">44</option>
<option value="45">45</option>
<option value="46">46</option>
<option value="47">47</option>
<option value="48">48</option>
<option value="49">49</option>
<option value="50">50</option>
<option value="51">51</option>
<option value="52">52</option>
<option value="53">53</option>
<option value="54">54</option>
<option value="55">55</option>
<option value="56">56</option>
<option value="57">57</option>
<option value="58">58</option>
<option value="59">59</option>
<option value="60">60</option>
</select>　


<script>
  $(function() {
    setInterval(function(){
      var now = new Date();
      $('#time').innerHTML = now.toLocaleTimeString();
    },1000);
    $('select').change(function() {
    var val = $(this).val();
    $('p').text(val);
    })
  })
    
</script>

app/views/pages/top.html.erb
<div class="field">
<h2>Threee</h2>

<% if user_signed_in? %>
  <% if current_user.admin %>
    <p>（管理者権限ありでログイン中）</p>
    <p><%= link_to '管理画面', rails_admin_path %></p>
  <% else %>
    <p>（ログイン中）</p>
  <% end %>
<% else %>
  <%= link_to '一般ゲストログイン（閲覧用）', pages_guest_sign_in_path, method: :post %>|
  <%= link_to '管理者ゲストログイン（閲覧用）', pages_admin_guest_sign_in_path, method: :post %>
<% end %>
<br>
<div class="hov">
<p>箇条書きアプリ</p>
<br><br>

<p>今自分が気にしていたいテーマを３つ箇条書きにして書くアプリケーションです。</p>

<p>
例えば、家事や作業、趣味など日ごろ自分が続けていることについて
自分でテーマを設定して作業中や作業後に思い出しやすくしてくれます。
</p>
<p>
テーマについて考え込むことよりも数をこなすことが重要だと考えて
3つのテーマに制限し、ユーザーからみてシンプルな設計をめざしました。

</p>
<p>ぜひ、このアプリケーションを使ってみてください</p>
<br>

<h3><%= link_to '新規作成', new_project_path, class: 'new_project' %></h3>
</div>

</div>