config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'pages#top'
  devise_for :users
  post '/pages/guest_sign_in', to: 'pages#guest_sign_in'
  post '/pages/admin_guest_sign_in', to: 'pages#admin_guest_sign_in'
  get 'top', to: 'pages#top', as: :top 
  get 'user/:id/my_page', to: 'pages#my_page', as: :my_page 
  resources :projects, shallow: true do
    resources :themes, except: :show
    collection do
      get 'search'
    end
    member do
      get 'public_on', to: 'projects#public_on', as: :public_on 
      get 'public_off', to: 'projects#public_off', as: :public_off 
    end
  end
  get 'user/:user_id/theme/:id', to: 'themes#show', as: :three 
  get 'threee/slide', to: 'pages#slide', as: :slide 
  resources :favorites, only: %i[index create destroy]
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
end

app/models/project.rb
class Project < ApplicationRecord
  validates :title, presence: true, length: { in: 1..255 }
  belongs_to :user
  has_many :themes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  accepts_nested_attributes_for :themes, allow_destroy: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy public_on public_off]
  before_action :set_q, only: %i[index search]
  before_action :check_user, only: %i[edit update destory]
  skip_before_action :authenticate_user!, only: :index

  def index
    @projects = Project.where(public: true).order(created_at: :desc).includes(:user, :themes)
  end

  def show
    @themes = @project.themes.order(created_at: :desc)
    @theme = @themes.first
    @theme_ids = @themes.map{|t| t.id }
    @back_id = @theme_ids[@theme_ids.index(@theme.id)+1]
    @next_id = @theme_ids[@theme_ids.index(@theme.id)-1]
  end

  def new
    @project = Project.new
    @project.themes.new
  end

  def create
    @project = current_user.projects.build(project_params)
    @theme = @project.themes.order(created_at: :desc).first
    respond_to do |format|
      if @project.save
        format.html { redirect_to  projects_path, notice: "プロジェクトが作成されました" }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @projects = current_user.projects.order(created_at: :desc).includes(:user, :themes)
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to  my_page_path(@project.user), notice: "タイトルが編集されました" }
        format.json { render :show, status: :ok, location: @theme }
      else
        format.html { redirect_to  edit_project_path(@project), notice: "タイトルが編集されませんでした" }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to  projects_path, notice: "プロジェクトが削除されました" }
      format.json { head :no_content }
    end
  end

  def search
    @results = @q.result
    @results = @results.where(public: true).order(created_at: :desc).includes(:user, :themes)
  end

  def public_on
    @project.public = true
    @project.save
  end

  def public_off
    @project.public = false
    @project.save
  end

  private

  def check_user
    unless @project.user_id == current_user.id
      redirect_to my_page_path(@project.user_id), notice: '他のユーザーではできない処理です'
    end
  end

  def set_project
    @project = Project.find(params[:id])
  end

  def set_q
    @q = Project.ransack(params[:q])
  end

  def project_params
    params.require(:project).permit(:title, themes_attributes: [:first_theme, :second_theme, :third_theme])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_fav_flash.html.erb
<div class="fav-flash" id="notice">
  <p>お気に入り登録されました</p>
</div>

app/views/projects/_favorite.html.erb
<%= link_to favorites_path(project_id: project.id), id: "fav-#{project.id}", remote: true, method: :post do %>
  <p>
    <div class="field center">
      <h1 class="fav-false">❤</h1>
    </div>
  </p>
<% end %>

app/views/projects/_non_fav_flash.html.erb
<div class="fav-flash" id="notice">
  <p>お気に入りが解除されました</p>
</div>

app/views/projects/_non_favorite.html.erb
<%= link_to favorite_path(project.id), id: "fav-#{project.id}", remote: true, method: :delete do %>
  <p>
    <div class="field center">
      <h1 class="fav-true">❤</h1>
    </div>
  </p>
<% end %>

app/views/projects/_non_pub_flash.html.erb
<div class="pub-flash" id="notice">
  <p>非公開になりました</p>
</div>

app/views/projects/_private.html.erb
<%= link_to 'OFF', public_on_project_path(project), id: "pub-#{project.id}", class: "pub-off", remote: true %>

app/views/projects/_pub_flash.html.erb
<div class="pub-flash" id="notice">
  <p>プロジェクトリストに公開されました</p>
</div>

app/views/projects/_public.html.erb
<%= link_to 'ON', public_off_project_path(project), id: "pub-#{project.id}", class: "pub-on", remote: true %>

app/views/projects/edit.html.erb
<div class="field">
<h1><%= @project.user.name %>さんのマイページ</h1>
<h3><%= link_to 'お気に入りのプロジェクト', favorites_path %></h3>
<%= form_with(model: @project) do |form| %>

<table class="field table-fixed">
  <thead>
    <tr>
        <th>公開</th>
        <th class="col-8">タイトル</th>
        <th class="col-1"></th>
        <th></th>
        <th></th>
        <th>変更回数</th>
        <th>作成日時</th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
          <td>
            <% if project.public %>
              <%= render 'projects/public', {project: project} %>
            <% else %>
              <%= render 'projects/private', {project: project} %>
            <% end %>
          </td>
        <% if @project.id==project.id %>
          <div class="field">
            <td>
              <h3><%= form.text_field :title, class: "theme_field edit_form" %></h3>
            </td>
            <td>
              <p><%= form.submit %></p>
            </td>
            <td>
              <p><%= link_to '削除する', project, method: :delete, data: { confirm: '本当に削除しますか？' } %></p>
            </td>
          </div>
        <% else %>
          <td>
            <h3 style="color: #bbb;">
              <%= project.title %>
            </h3>
          </td>
          <td>
            <p><%= link_to '名前を編集する', edit_project_path(project) %></p>
          </td>
          <td>
            <p><%= link_to '削除する', project, method: :delete, data: { confirm: 'Are you sure?' } %></p>
          </td>
        <% end %>
        <td><%= link_to '履歴', project_themes_path(project) %></td>
        <td><%= project.themes.length %></td>
        <td><%= project.created_at.in_time_zone('Tokyo').strftime("%Y年%m月%d日 %H:%M:%S") %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<br>

<%= link_to 'New Project', new_project_path %>

</div>

app/views/projects/index.html.erb
<div class="field">
  <h1>プロジェクト　リスト</h1>
  <% unless current_user==nil %>
    <%= search_form_for @q, url: search_projects_path do |f| %>
      <%= f.label :title_cont, 'タイトル検索' %>
      <%= f.search_field :title_cont, placeholder: "プロジェクトのタイトル" %>
      <br>
      <%= f.submit '検索' %>
    <% end %>
  <% end %>
  
  <table class="field table-fixed">
    <thead>
      <tr>
      <th></th>
        <th>名前</th>
        <th>タイトル</th>
        <th>変更回数</th>
        <th>作成日時</th>
      </tr>
    </thead>
  
    <tbody>
      <% @projects.each do |project| %>
        <tr>
          
          <% if current_user==nil %>
            <td><h1>👤</h1></td>
            <td><%= link_to project.user.name, my_page_path(project.user) %></td>
            <td><%= link_to project.title, three_path(project.user.id, project.themes.order(created_at: :desc).first.id) %></td>
          <% else %>
          
          <td>
            <% if project.user ==current_user %>
              <h1>👤</h1>
            <% elsif Favorite.exists?(user_id: current_user.id, project_id: project.id) %>
              <%= render 'projects/non_favorite', {project: project} %>
            <% else %>
              <%= render 'projects/favorite', {project: project} %>
            <% end %>
          </td>
          <td><%= link_to project.user.name, my_page_path(project.user) %></td>
          <td>
            <h3>
              <% if project.user == current_user && project.themes.count==0 %>
                <%= link_to project.title, new_project_path %>
              <% else %>
                <%= link_to project.title, three_path(project.user.id, project.themes.order(created_at: :desc).first.id) %>
              <% end %>
            </h3>
          </td>
          <% end %>
          <td><%= project.themes.length %></td>
          <td>
            <p>
            【作成日時】:<%= project.created_at.in_time_zone('Tokyo').strftime("%Y年%m月%d日 %H:%M:%S") %>
            </p>
            <% if project.themes.length > 1 %>
              <p>
              【変更日時】:<%= project.themes.order(created_at: :desc).first.created_at.in_time_zone('Tokyo').strftime("%Y年%m月%d日 %H:%M:%S") %>
              </p>
            <% end %>
          </td>
        </tr>
      </tbody>
    <% end %>
  </table>
  
  <br>
  
  <%= link_to '新規作成', new_project_path %>
  
</div>

app/views/projects/new.html.erb
<p style="margin: 0;">プロジェクトを作成してください</p>
<p style="margin: 0;">さらに、３つのテーマを登録してください</p>
<p>↓↓↓↓↓</p>


<%= form_with(model: @project) do |form| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "件のエラー") %>があります</h2>
      <ul>
        <% @project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h2><%= form.text_field :title ,class: "theme_field project", placeholder: "プロジェクト名" %></h2>
  

  <%= form.fields_for :themes do | form | %>
    <ul>
      <li>
        <h3>
          <div class="field">
            <%= form.text_field :first_theme ,class: "theme_field first_theme", placeholder: "テーマ　①"%>
          </div>
        </h3>
      </li>
      <li>
        <h3>
          <div class="field">
            <%= form.text_field :second_theme ,class: "theme_field second_theme", placeholder: "テーマ　②"%>
          </div>
        </h3>
      </li>
      <li>
        <h3>
          <div class="field">
            <%= form.text_field :third_theme  ,class: "theme_field third_theme", placeholder: "テーマ　③"%>
          </div>
        </h3>
      </li>
    </ul>
  <% end %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<%= link_to '戻る',  projects_path %>
</div>

app/views/projects/public_off.js.erb
$('#pub-<%= @project.id %>').replaceWith("<%= escape_javascript(render 'projects/private', {project: @project}) %>");
$('.pub-flash').replaceWith("<%= escape_javascript(render 'projects/non_pub_flash') %>");

app/views/projects/public_on.js.erb
$('#pub-<%= @project.id %>').replaceWith("<%= escape_javascript(render 'projects/public', {project: @project}) %>");
$('.pub-flash').replaceWith("<%= escape_javascript(render 'projects/pub_flash') %>");

app/views/projects/search.html.erb
<div class="field">
  <h1>プロジェクト　リスト</h1>
  
  <%= search_form_for @q, url: search_projects_path do |f| %>
    <%= f.label :title_cont, 'タイトル検索' %>
    <%= f.search_field :title_cont %>
    <br>
    <%= f.submit '検索' %>
  <% end %>
  
  <table class="field">
    <thead>
      <tr>
      <th></th>
        <th>名前</th>
        <th>タイトル</th>
        <th>変更回数</th>
        <th>作成日時</th>
      </tr>
    </thead>
  
    <tbody>
      <% @results.each do |project| %>
        <tr>
          <td>
            <% if project.user ==current_user %>
              <h1>👤</h1>
            <% elsif Favorite.exists?(user_id: current_user.id, project_id: project.id) %>
              <%= render 'projects/non_favorite', {project: project} %>
            <% else %>
              <%= render 'projects/favorite', {project: project} %>
            <% end %>
          </td>
          <td><%= link_to project.user.name, my_page_path(project.user) %></td>
          <td>
            <h3>
              <% if project.user == current_user && project.themes.count==0 %>
                <%= link_to project.title, new_project_path %>
              <% else %>
                <%= link_to project.title, three_path(project.user.id, project.themes.order(created_at: :desc).first.id) %>
              <% end %>
            </h3>
          </td>
          <td><%= project.themes.length %></td>
          <td>
            <p>
            【作成日時】:<%= project.created_at.in_time_zone('Tokyo').strftime("%Y年%m月%d日 %H:%M:%S") %>
            </p>
            <% if project.themes.length > 1 %>
            <p>
            【変更日時】:<%= project.themes.order(created_at: :desc).first.created_at.in_time_zone('Tokyo').strftime("%Y年%m月%d日 %H:%M:%S") %>
            </p>
            <% end %>
          </td>
        </tr>
      </tbody>
    <% end %>
  </table>
  
  <br>
  
  <%= link_to '新規作成', new_project_path %>
  
</div>