config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'pages#top'
  devise_for :users
  post '/pages/guest_sign_in', to: 'pages#guest_sign_in'
  post '/pages/admin_guest_sign_in', to: 'pages#admin_guest_sign_in'
  get 'top', to: 'pages#top', as: :top 
  get 'user/:id/my_page', to: 'pages#my_page', as: :my_page 
  resources :projects, shallow: true do
    resources :themes, except: :show
    collection do
      get 'search'
    end
    member do
      get 'public_on', to: 'projects#public_on', as: :public_on 
      get 'public_off', to: 'projects#public_off', as: :public_off 
    end
  end
  get 'user/:user_id/theme/:id', to: 'themes#show', as: :three 
  get 'threee/slide', to: 'pages#slide', as: :slide 
  resources :favorites, only: %i[index create destroy]
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThreeeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="header navbar navbar-light bg-light" >
      <div class="container-fluid">
          <%= button_to "Threee", top_path, {method: :get, class: "btn btn-outline-dark"} %>
          <%= button_to "Slide", slide_path, {method: :get, class: "btn btn-light"} %>
        <% if user_signed_in? %>
          <%= button_to "お気に入りのプロジェクト", favorites_path, {method: :get, class: "btn btn-light"} %>
          <%= button_to "プロジェクト", projects_path, {method: :get, class: "btn btn-light"} %>
          <%= button_to "マイページ", my_page_path(current_user), {method: :get, class: "btn btn-light"} %>
          <%= button_to "ログアウト", destroy_user_session_path, class: "btn btn-light logout", method: :delete %>
        <% else %>
          <%= button_to "プロジェクト", projects_path, {method: :get, class: "btn btn-light"} %>
          <%= button_to "新規登録", new_user_registration_path, {method: :get, class: "btn btn-light"} %>
          <%= button_to "ログイン", new_user_session_path, {method: :get, class: "btn btn-light"} %>
        <% end %>
      </div>
    </nav>
    <div class="css-body field">
      <div class="fav-flash pub-flash">
        <% if notice %>
          <p class="alert alert-notice" id="notice"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-error" id="alert"><%= alert %></p>
        <% end %>
      </div>
      <%= yield %>
        
    </div>
    <footer class="footer bg-light text-center text-lg-start">
  
      <div class="text-center p-3" >
        © 2022 Copyright: Threee
      </div>
    </footer>
  </body>
</html>